# <center> Основные понятия линейной алгебры: векторы и действия над ними

In [2]:
import numpy as np
import pandas as pd
s = np.array([33, 64, 50, 45])
print('Третья координата вектора s: ', s[2], '\nРазмерность вектора s: ', len(s), sep='')

Третья координата вектора s: 50
Размерность вектора s: 4


## Сложение и вычитание векторов

In [3]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
print('Результат сложения векторов', a + b)
print('Результат вычитания векторов', a - b)

Результат сложения векторов [15 23 14  8]
Результат вычитания векторов [ 5 -7 -4 -6]


## Умножение вектора на скаляр

In [4]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
print('Результат умножения вектора на число:', c)

Результат умножения вектора на число: [24.   9.  13.6]


## Линейная комбинация

In [5]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
print('Линейная комбинация векторов:', u)

Линейная комбинация векторов: [1800 3000 2700]


## Скалярное произведение векторов
`np.dot()`

In [6]:
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
s = np.dot(a, w)
print('Скалярное произведение векторов:', s)

Скалярное произведение векторов: 102.0


## Примеры
### 1

In [7]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40],
    '7.Duration': [10, 20, 30, 15, 5, 40, 20, 8, 20]
})
Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area  7.Duration
0      65      50        3        5                 8          37          10
1      70      52        2       12                 4          40          20
2     120      80        1       10                 5          65          30
3      35      33        1        3                10          20          15
4      40      33        1        6                20          16           5
5      50      44        2       13                12          35          40
6     100      80        4        8                 5          60          20
7      90      65        3       21                 1          50           8
8      85      65        2        5                10          40          20

In [8]:
print('Вектор квартиры №5:', Hut_Paradise_DF.values[4, :])

Вектор квартиры №5: [40 33  1  6 20 16  5]


In [9]:
print('Вектор этажей всех квартир:', Hut_Paradise_DF.values[:, 3])

Вектор этажей всех квартир: [ 5 12 10  3  6 13  8 21  5]


In [10]:
print('Вектор нежилой площади:', (Hut_Paradise_DF['2.Area'] - Hut_Paradise_DF['6.Liv.Area']).values)

Вектор нежилой площади: [13 12 15 13 17  9 20 15 25]


In [11]:
total_demo_minutes = Hut_Paradise_DF['5.Demo two weeks'].values @ Hut_Paradise_DF['7.Duration'].values
print('Продолжительность просмотров в минутах во всех квартирах за две недели:', total_demo_minutes)

Продолжительность просмотров в минутах во всех квартирах за две недели: 1348


### 2

In [12]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

w_0 = 2
w_1 = -3

vw = w_0*v + w_1*w
print('Линейная комбинация векторов v и w:', vw)
print('Скалярное произведение vw с u:', vw @ u)

Линейная комбинация векторов v и w: [-3 14  3  4  2]
Скалярное произведение vw с u: 0


# <center>Матрицы и базовые действия с ними

In [13]:
A = np.array([
    [1, -5, 3], 
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])
print('Matrix A:\n', A, sep='')
print('Shape of matrix A:', A.shape)
print(
    'a_23=', A[1, 2],
    ' a_32=', A[2, 1], 
    ' a_33=', A[2,2], sep=''
)


Matrix A:
[[ 1 -5  3]
 [ 2  2  1]
 [ 0  3  1]
 [ 2  4 12]]
Shape of matrix A: (4, 3)
a_23=1 a_32=3 a_33=1


### 5

In [14]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])


In [15]:
inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income]).T
inc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [16]:
cons = np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption]).T
cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [17]:
tax = 0.13
inc_after_tax = (1 - tax) * inc
inc_after_tax

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [18]:
balance = inc_after_tax - cons
balance

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

## Произведение матриц

In [19]:
A = np.matrix("1, -5; 2, 2; 0, 3")
B = np.matrix("3, 1, 0; -1, 0, 2")
print('A * B')
print(np.dot(A, B))
print('-' * 20)
print('B * A')
print(np.dot(B, A))

A * B
[[  8   1 -10]
 [  4   2   4]
 [ -3   0   6]]
--------------------
B * A
[[  5 -13]
 [ -1  11]]


In [20]:
A = np.array([
    [1, -1, 2, 4, 0], 
    [8, 2, 0, 5, 3],
    [0, 1, 2, 1, 2]
])
B = np.array([
    [1, 0, 1, 0],
    [0, 0, 2, -1],
    [1, 0, 1, 1],
    [0, 1, 1, 1],
    [1, 1, 0, -1]
])
np.dot(A, B)

array([[ 3,  4,  5,  7],
       [11,  8, 17,  0],
       [ 4,  3,  5,  0]])

## Матрица Грама

In [21]:
a, b, c = np.array([1, 1]), np.array([2, -1]), np.array([1, 2])
A = np.array([a, b, c]).T
gram_A = A.T @ A
gram_A

array([[2, 1, 3],
       [1, 5, 0],
       [3, 0, 5]])

## Практика
### 7.1

In [22]:
A = np.array([
    [5,-1,3,1,2],
    [-2,8,5,-1,1]
])
x = np.array([1,2,3,4,5])
A @ x

array([26, 30])

### 7.2

In [23]:
A = np.array([
    [1,9,8,5],
    [3,6,3,2],
    [3,3,3,3],
    [0,2,5,9], 
    [4,4,1,2]
])
B = np.array([
    [1,-1,0,1,1],
    [-2,0,2,-1,1]
])
B @ A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

### 7.3

In [24]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])
A = np.array([x, y, z])
gram_columns_A = A.T @ A
gram_columns_A

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

### 7.4, 7.5
* В DataFrame `Count_DF` содержится информация по количеству услуг, оказанных каждым стилистом за апрель.
* В DataFrame `Price_DF` содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.

In [25]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1]) # вектор комиссий
display(Count_DF)
display(Price_DF)

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5          2.0      1.0   1.5
Егор               5.0              5.0          3.0      2.0   2.5
Женя               1.1              1.0          1.5      0.5   1.7
Юра                4.5              4.0          2.5      1.0   2.0

In [26]:
result_df = Count_DF * Price_DF
result_df

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня               20.0              7.5         12.0     12.0  10.0
Борис              3.6             52.5          3.0     25.0   6.0
Вика              24.0             24.0          0.0     15.0   8.0
Галя               7.2              9.6         50.4     11.2  10.0
Дима              15.0             87.5         54.0     25.0  27.0
Егор              50.0             15.0          6.0     34.0  30.0
Женя              24.2              1.0          6.0     12.5  34.0
Юра               31.5              0.0         77.5     31.0  56.0

In [27]:
total_income = result_df @ com
total_income.values

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [28]:
total_salary = result_df @ (np.ones(shape=com.shape) - com)
total_salary.values

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

## Обратная матрица

In [35]:
A = np.matrix('1,2,3; 4,5,6; 7, 8, 10')
np.linalg.inv(A)

matrix([[-0.66666667, -1.33333333,  1.        ],
        [-0.66666667,  3.66666667, -2.        ],
        [ 1.        , -2.        ,  1.        ]])

## Определитель

In [36]:
A = np.matrix ("1, 2, 3; 4, 5, 6 ; 7, 8, 10")
np.linalg.det(A)

-2.9999999999999996

In [37]:
A = np.array([
    [1, 2],
    [1, 1]
])
B = np.array([
    [5, -2],
    [-1, 4]
])
print('det(A)')
display(np.linalg.det(A))
print('det(B)')
display(np.linalg.det(B))
print('det(A+B)')
display(np.linalg.det(A+B))

det(A)


-1.0

det(B)


17.999999999999996

det(A+B)


29.99999999999999