# <center> Основные понятия линейной алгебры: векторы и действия над ними

In [1]:
import numpy as np
s = np.array([33, 64, 50, 45])
print('Третья координата вектора s: ', s[2], '\nРазмерность вектора s: ', len(s), sep='')

Третья координата вектора s: 50
Размерность вектора s: 4


## Сложение и вычитание векторов

In [2]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
print('Результат сложения векторов', a + b)
print('Результат вычитания векторов', a - b)

Результат сложения векторов [15 23 14  8]
Результат вычитания векторов [ 5 -7 -4 -6]


## Умножение вектора на скаляр

In [3]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
print('Результат умножения вектора на число:', c)

Результат умножения вектора на число: [24.   9.  13.6]


## Линейная комбинация

In [4]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
print('Линейная комбинация векторов:', u)

Линейная комбинация векторов: [1800 3000 2700]


## Скалярное произведение векторов
`np.dot()`

In [5]:
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
s = np.dot(a, w)
print('Скалярное произведение векторов:', s)

Скалярное произведение векторов: 102.0


## Примеры
### 1

In [6]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40],
    '7.Duration': [10, 20, 30, 15, 5, 40, 20, 8, 20]
})
Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area  7.Duration
0      65      50        3        5                 8          37          10
1      70      52        2       12                 4          40          20
2     120      80        1       10                 5          65          30
3      35      33        1        3                10          20          15
4      40      33        1        6                20          16           5
5      50      44        2       13                12          35          40
6     100      80        4        8                 5          60          20
7      90      65        3       21                 1          50           8
8      85      65        2        5                10          40          20

In [7]:
print('Вектор квартиры №5:', Hut_Paradise_DF.values[4, :])

Вектор квартиры №5: [40 33  1  6 20 16  5]


In [8]:
print('Вектор этажей всех квартир:', Hut_Paradise_DF.values[:, 3])

Вектор этажей всех квартир: [ 5 12 10  3  6 13  8 21  5]


In [9]:
print('Вектор нежилой площади:', (Hut_Paradise_DF['2.Area'] - Hut_Paradise_DF['6.Liv.Area']).values)

Вектор нежилой площади: [13 12 15 13 17  9 20 15 25]


In [10]:
total_demo_minutes = Hut_Paradise_DF['5.Demo two weeks'].values @ Hut_Paradise_DF['7.Duration'].values
print('Продолжительность просмотров в минутах во всех квартирах за две недели:', total_demo_minutes)

Продолжительность просмотров в минутах во всех квартирах за две недели: 1348


### 2

In [11]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

w_0 = 2
w_1 = -3

vw = w_0*v + w_1*w
print('Линейная комбинация векторов v и w:', vw)
print('Скалярное произведение vw с u:', vw @ u)

Линейная комбинация векторов v и w: [-3 14  3  4  2]
Скалярное произведение vw с u: 0


# <center>Матрицы и базовые действия с ними

In [18]:
A = np.array([
    [1, -5, 3], 
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])
print('Matrix A:\n', A, sep='')
print('Shape of matrix A:', A.shape)
print(
    'a_23=', A[1, 2],
    ' a_32=', A[2, 1], 
    ' a_33=', A[2,2], sep=''
)


Matrix A:
[[ 1 -5  3]
 [ 2  2  1]
 [ 0  3  1]
 [ 2  4 12]]
Shape of matrix A: (4, 3)
a_23=1 a_32=3 a_33=1
