# <center>Линейная алгебра в контексте линейных методов. Часть II
## <center>Неоднородные СЛАУ
### <center>Случай «ИДЕАЛЬНАЯ ПАРА»

In [11]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
A = np.array([
    [4, 7],
    [5, 10]
])
b = np.array([[20, 30]]).reshape(2, 1)
Ab = np.append(A, b, axis=1)
num_of_unk_var = len(A[0])
rank_a = np.linalg.matrix_rank(A)
rank_ab = np.linalg.matrix_rank(Ab)
print('matrix A:\n', A, sep='')
print('\nvector b:\n', b, sep='')
print('\nrank(A):', rank_a)
print('\nrank(A|b):', rank_ab)
print('\nNumber of unknown variables:', num_of_unk_var)
xy = np.linalg.inv(A) @ b
print('\nOnly decision')
print(xy)

matrix A:
[[ 4  7]
 [ 5 10]]

vector b:
[[20]
 [30]]

rank(A): 2

rank(A|b): 2

Number of unknown variables: 2

Only decision
[[-2.]
 [ 4.]]


### <center>Случай «В АКТИВНОМ ПОИСКЕ»

In [3]:
A = np.array([
    [4, 7, -1],
    [2, 1, 1]
])
b = np.array([[7, 2]]).reshape(2, 1)
Ab = np.append(A, b, axis=1)
num_of_unk_var = len(A[0])
rank_a = np.linalg.matrix_rank(A)
rank_ab = np.linalg.matrix_rank(Ab)
print('matrix A:\n', A, sep='')
print('\nvector b:\n', b, sep='')
print('\nrank(A):', rank_a)
print('\nrank(A|b):', rank_ab)
print('\nNumber of unknown variables:', num_of_unk_var)
print('\nInfinity decisions')

matrix A:
[[ 4  7 -1]
 [ 2  1  1]]

vector b:
[[7]
 [2]]

rank(A): 2

rank(A|b): 2

Number of unknown variables: 3

Infinity decisions


In [4]:
# 2.6
A = np.array([
    [4, 7, -1],
    [-4, 2, 5],
    [0, 9, 4]
])
b = np.array([7, 3, 10]).reshape(3, 1)
Ab = np.append(A, b, axis=1)
num_of_unk_var = len(A[0])
rank_a = np.linalg.matrix_rank(A)
rank_ab = np.linalg.matrix_rank(Ab)
print('matrix A:\n', A, sep='')
print('\nvector b:\n', b, sep='')
print('\nrank(A):', rank_a)
print('\nrank(A|b):', rank_ab)
print('\nNumber of unknown variables:', num_of_unk_var)
print('\nInfinity decisions')

matrix A:
[[ 4  7 -1]
 [-4  2  5]
 [ 0  9  4]]

vector b:
[[ 7]
 [ 3]
 [10]]

rank(A): 2

rank(A|b): 2

Number of unknown variables: 3

Infinity decisions


### <center>Случай «ВСЁ СЛОЖНО». OLS

In [5]:
# 2.9
A = np.array([
    [1, -5],
    [2, 1],
    [1, 1]
])
b = np.array([1, 2, 2])
widehat_w = np.array([1, 1])
error_vec = (b - (A @ widehat_w)).reshape(3, 1)
print('Error vector:\n', error_vec, sep='')

Error vector:
[[ 5]
 [-1]
 [ 0]]


In [6]:
# 2.11
A = np.array([
    [1, 2],
    [-3, 1],
    [1, 2],
    [1, -1]
])
b = np.array([1, 4, 5, 0]).reshape(len(A), 1)
gram_matrix = A.T @ A
inv_gram = np.linalg.inv(gram_matrix)
scalar_columns_b = A.T @ b
hat_omega = inv_gram @ scalar_columns_b
print(
    'matrix A:\n', A, 
    '\n\nvector b:\n', b,
    '\n\nGram matrix for columns:\n', gram_matrix,
    '\n\nInverted gram matrix:\n', inv_gram,
    '\n\nA^T * b:\n', scalar_columns_b,
    '\n\nPredicted coeffs omega:\n', hat_omega, sep=''
)



matrix A:
[[ 1  2]
 [-3  1]
 [ 1  2]
 [ 1 -1]]

vector b:
[[1]
 [4]
 [5]
 [0]]

Gram matrix for columns:
[[12  0]
 [ 0 10]]

Inverted gram matrix:
[[0.08333333 0.        ]
 [0.         0.1       ]]

A^T * b:
[[-6]
 [16]]

Predicted coeffs omega:
[[-0.5]
 [ 1.6]]


## <center>Линейная регрессия

In [9]:
# 3.5
data = np.array([[1, 0.2, 6]])
w_hat = np.array([[-29.3, -0.26, 8.4]]).reshape(3, 1)
data @ w_hat

array([[21.048]])

### Особенности класса `LinearRegression`

In [10]:
# создадим вырожденную матрицу А
A = np.array([
    [1, 1, 1, 1], 
    [2, 1, 1, 2], 
    [-2, -1, -1, -2]]
).T
y = np.array([1, 2, 5, 1])
# вычислим OLS-оценку для коэффициентов
w_hat=np.linalg.inv(A.T@A)@A.T@y
print(w_hat) 

LinAlgError: Singular matrix

**Сингулярное разложение (SVD)**

In [12]:
# создаём модель линейной регрессии
model = LinearRegression(fit_intercept=False)
# вычисляем коэффициенты регрессии
model.fit(A, y)
print('w_hat:', model.coef_)

w_hat: [ 6.   -1.25  1.25]


**Сингулярное разложение** зашито в функцию `np.linalg.lstsq()`, которая позволяет в одну строку построить модель линейной регрессии по МНК:

In [13]:
# классическая OLS-регрессия в numpy с возможностью получения решения даже для вырожденных матриц
np.linalg.lstsq(A, y, rcond=None)

(array([ 6.  , -1.25,  1.25]),
 array([], dtype=float64),
 2,
 array([4.86435029e+00, 5.81460412e-01, 3.42443768e-17]))

Функция возвращает четыре значения:

* вектор рассчитанных коэффициентов линейной регрессии;
* сумму квадратов ошибок, $MSE$ (она не считается, если ранг матрицы $A$ меньше числа неизвестных, как в нашем случае);
* ранг матрицы $A$;
* вектор из сингулярных значений, которые как раз и оберегают нас от ошибки.
