# <center>Линейная алгебра в контексте линейных методов. Часть II
## <center>Неоднородные СЛАУ
### <center>Случай «ИДЕАЛЬНАЯ ПАРА»

In [47]:
import numpy as np

In [48]:
A = np.array([
    [4, 7],
    [5, 10]
])
b = np.array([[20, 30]]).reshape(2, 1)
Ab = np.append(A, b, axis=1)
num_of_unk_var = len(A[0])
rank_a = np.linalg.matrix_rank(A)
rank_ab = np.linalg.matrix_rank(Ab)
print('matrix A:\n', A, sep='')
print('\nvector b:\n', b, sep='')
print('\nrank(A):', rank_a)
print('\nrank(A|b):', rank_ab)
print('\nNumber of unknown variables:', num_of_unk_var)
xy = np.linalg.inv(A) @ b
print('\nOnly decision')
print(xy)

matrix A:
[[ 4  7]
 [ 5 10]]

vector b:
[[20]
 [30]]

rank(A): 2

rank(A|b): 2

Number of unknown variables: 2

Only decision
[[-2.]
 [ 4.]]


### <center>Случай «В АКТИВНОМ ПОИСКЕ»

In [49]:
A = np.array([
    [4, 7, -1],
    [2, 1, 1]
])
b = np.array([[7, 2]]).reshape(2, 1)
Ab = np.append(A, b, axis=1)
num_of_unk_var = len(A[0])
rank_a = np.linalg.matrix_rank(A)
rank_ab = np.linalg.matrix_rank(Ab)
print('matrix A:\n', A, sep='')
print('\nvector b:\n', b, sep='')
print('\nrank(A):', rank_a)
print('\nrank(A|b):', rank_ab)
print('\nNumber of unknown variables:', num_of_unk_var)
print('\nInfinity decisions')

matrix A:
[[ 4  7 -1]
 [ 2  1  1]]

vector b:
[[7]
 [2]]

rank(A): 2

rank(A|b): 2

Number of unknown variables: 3

Infinity decisions


In [50]:
# 2.6
A = np.array([
    [4, 7, -1],
    [-4, 2, 5],
    [0, 9, 4]
])
b = np.array([7, 3, 10]).reshape(3, 1)
Ab = np.append(A, b, axis=1)
num_of_unk_var = len(A[0])
rank_a = np.linalg.matrix_rank(A)
rank_ab = np.linalg.matrix_rank(Ab)
print('matrix A:\n', A, sep='')
print('\nvector b:\n', b, sep='')
print('\nrank(A):', rank_a)
print('\nrank(A|b):', rank_ab)
print('\nNumber of unknown variables:', num_of_unk_var)
print('\nInfinity decisions')

matrix A:
[[ 4  7 -1]
 [-4  2  5]
 [ 0  9  4]]

vector b:
[[ 7]
 [ 3]
 [10]]

rank(A): 2

rank(A|b): 2

Number of unknown variables: 3

Infinity decisions


### <center>Случай «ВСЁ СЛОЖНО». OLS

In [51]:
# 2.9
A = np.array([
    [1, -5],
    [2, 1],
    [1, 1]
])
b = np.array([1, 2, 2])
widehat_w = np.array([1, 1])
error_vec = (b - (A @ widehat_w)).reshape(3, 1)
print('Error vector:\n', error_vec, sep='')

Error vector:
[[ 5]
 [-1]
 [ 0]]


In [52]:
# 2.11
A = np.array([
    [1, 2],
    [-3, 1],
    [1, 2],
    [1, -1]
])
b = np.array([1, 4, 5, 0]).reshape(len(A), 1)
gram_matrix = A.T @ A
inv_gram = np.linalg.inv(gram_matrix)
scalar_columns_b = A.T @ b
hat_omega = inv_gram @ scalar_columns_b
print(
    'matrix A:\n', A, 
    '\n\nvector b:\n', b,
    '\n\nGram matrix for columns:\n', gram_matrix,
    '\n\nInverted gram matrix:\n', inv_gram,
    '\n\nA^T * b:\n', scalar_columns_b,
    '\n\nPredicted coeffs omega:\n', hat_omega,
    sep='')



matrix A:
[[ 1  2]
 [-3  1]
 [ 1  2]
 [ 1 -1]]

vector b:
[[1]
 [4]
 [5]
 [0]]

Gram matrix for columns:
[[12  0]
 [ 0 10]]

Inverted gram matrix:
[[0.08333333 0.        ]
 [0.         0.1       ]]

A^T * b:
[[-6]
 [16]]

Predicted coeffs omega:
[[-0.5]
 [ 1.6]]
